# Generated by Django 6.0.7 on 2026-08-15 07:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_article_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2026, 8, 15, 7, 55, 52, 949193, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(help_text='ENTER A VALID TITLE', max_length=70),
        ),
    ]
