# Generated by Django 6.0.7 on 2026-08-17 03:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0007_caregory_remove_article_pub_date_alter_article_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('des', models.TextField()),
            ],
        ),
    ]
