# Generated by Django 6.0.7 on 2026-08-17 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_new'),
    ]

    operations = [
        migrations.DeleteModel(
            name='New',
        ),
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
