# Generated by Django 6.0.7 on 2026-08-23 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='images/banners'),
        ),
    ]
