# Generated by Django 6.0.7 on 2026-08-23 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_article_banner'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Caregory',
            new_name='Category',
        ),
    ]
