# Generated by Django 6.0.7 on 2026-09-07 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_message_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='title',
        ),
        migrations.AddField(
            model_name='message',
            name='name',
            field=models.CharField(default='name', max_length=50),
        ),
    ]
