# Generated by Django 6.0.7 on 2026-09-07 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_remove_message_title_message_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='name',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
