# Generated by Django 6.0.7 on 2026-09-09 07:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_alter_message_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 9, 9, 7, 53, 13, 885926, tzinfo=datetime.timezone.utc)),
        ),
    ]
